// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Movie struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	MovieID       int32
	OriginalTitle string
	Title         string
	Overview      string
	ReleaseDate   string
	PosterPath    string
	VoteAverage   float64
	Imdb          string
	Tmdb          int32
	UserID        uuid.UUID
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Email        string
	PasswordHash string
}
