// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Movie struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	MovieID       int32
	OriginalTitle string
	Title         string
	Overview      string
	ReleaseDate   string
	PosterPath    string
	VoteAverage   float64
	Imdb          string
	Tmdb          int32
	UserID        uuid.UUID
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Email        string
	PasswordHash string
}
